### ISSUE TITLE
ur-new

### ISSUE THREAD

**Issue by suprstarrd** [rossjrw/ur#1191]
Assuming this won't work, but it's worth a test

**Comment by suprstarrd** [comment]
@rossjrw 

Context: A game was already ongoing, so this shouldn't have made a new game

It also refers to #1190 as the winning move, despite there being no winning move to begin with

**Comment by suprstarrd** [comment]
Might do a PR for this. Just to make it simple I could do a piece check, but I'm sure there's a much better way of doing it.

UPDATE: Yep, there's a much better way to do this. The event log shows this for the last event:
```
  {
    "username": "jbmagination",
    "issue": 1190,
    "time": "2021-10-25T13:27:26.292Z",
    "team": "b",
    "action": "move",
    "boardImage": null,
    "events": {
      "rosetteClaimed": false,
      "captureHappened": false,
      "ascensionHappened": false,
      "gameWon": false
    },
    "fromPosition": 10,
    "toPosition": 13,
    "roll": 3
  }
]
```

Checking for `events.gameWon` would probably do the trick.

**Comment by rossjrw** [comment]
LMAO. I can't believe I didn't think to account for this. Thanks for the ping, I appreciate it.

I've reverted the game back to where it was in game 8, erasing game 9 from history - yourself and @nirakon should feel free to recreate your feud here.

I'd love a PR if you have the time!

For reference: [state of the game before the wipe](https://github.com/rossjrw/rossjrw/tree/e93b952b7365986a16377a357b78e254cd640163) - [board before the wipe](https://raw.githubusercontent.com/rossjrw/rossjrw/e93b952b7365986a16377a357b78e254cd640163/games/current/board.1202.svg)

**Comment by suprstarrd** [comment]
I guess I'll call it game 8.5, then 😆

Not able to do a PR for about 3-4 hours<i></i>~~, I'm working right now-- will PR when free~~ 👍
