### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by suprstarrd** [rossjrw/ur#1216]
My notification feed currently looks like this:
![image](https://user-images.githubusercontent.com/26027089/138903125-8df269d1-a333-4f72-ad0b-0e9dcc2fc2b0.png)

And it makes it very hard to find the actual things I need to see, haha

I think the commit ping needs to go. Issues are rough because not only are comments real-time while commit pings are not, but also the closing of an issue also triggers a notification. Getting rid of the commit ping prevents the duplicate notification 👍 

I'm making an issue before a PR so I can see what other people think, or if I'm just being nitpicky and need to learn how to mark an issue/commit as done lol

**Comment by rossjrw** [comment]
I think you're probably right. I like being able to have a little user profile popup on each commit, but "I like" isn't enough to justify duplicated notifications.

**Comment by suprstarrd** [comment]
With #1271, the duplicated notifications suddenly look like a good idea-- although, it should probably commit *before* it comments. It looks to me like it makes the issue comment, closes the issue, *then* sends the changes for the commit.

**Comment by rossjrw** [comment]
> it should probably commit _before_ it comments.

Agreed - I've been looking into [move.ts/makeMove](https://github.com/rossjrw/rossjrw/blob/6b8085cbbb81929dbd8781fbd773098c6b96e5ed/src/move.ts#L16) for #1211 and that function does stuff in a really weird order, including some things that should be outside of its scope. I'm going to refactor it.
