### ISSUE TITLE
Workflow file susceptible to code injection

### ISSUE THREAD

**Issue by suprstarrd** [rossjrw/ur#1219]
See #1218 for more details + a code injection example in action.

Will look into how to "harden" this file and prevent it. Likely sanitization.

(Sorry for the label, thought it'd be fitting. Yes, it was added with code injection)

**Comment by suprstarrd** [comment]
Probably the fastest I've ever solved a security issue. (It was indeed a lack of sanitization.)

Will push a PR.

**Comment by rossjrw** [comment]
> (Sorry for the label, thought it'd be fitting. Yes, it was added with code injection)

Incredible
