### ISSUE TITLE
possible discord bot

### ISSUE THREAD

**Issue by Kitsuneko111** [rossjrw/ur#1314]
Random thoughts at 1am left me with the idea of a discord bot (or any other platform really I guess) that could follow the game and maybe even allow players to make moves.
Would be an interesting cross network between github and discord, not sure if you'd need a separate webhook for it or if it could even be built into the existing code

**Comment by suprstarrd** [comment]
This would mean that a single bot would need to be able to send an action to the repository-- or in the event of it being a separate GitHub app, being able to write whatever they want to the repository.

That's probably a big security problem for a Discord bot-- so following the game seems like a better idea, that just requires read-only access.

**Comment by rossjrw** [comment]
This is very much out of scope for this project. If you'd like to make a Discord bot that you can play Ur with, you could with https://www.npmjs.com/package/ur-game (which this project uses) and discord.js. If you want to make a Discord bot that follows the game happening in this repo specifically, I have no problem with that. No reason for that to be part of this project, though.
