### ISSUE TITLE
Track what happened in each event

### ISSUE THREAD

**Issue by rossjrw** [rossjrw/ur#330]
The event log keeps track of the string generated and logged in the README:

https://github.com/rossjrw/rossjrw/blob/3d17b2e87da20ec74aef464d7688548a855b7841/games/log.2020-07-30T14:24:20.028Z.json#L11-L19

Works great, but what if I want to change the string format? All of the old events will still use the previous format.

Instead, I should log the events object directly, and construct the string for each event each time the README is generated. This will also enable more fun stats e.g. counting the number of captures.

**Comment by rossjrw** [comment]
Closed in ec874ddd05d6604508ad3885c16eddd8da931b63 and 7fbe4ae23d91e882c5a278c4d70bb90692fb7d77:

https://github.com/rossjrw/rossjrw/blob/ec874ddd05d6604508ad3885c16eddd8da931b63/games/current/log.json#L2-L18

**Comment by 1ethanhansen** [comment]
It looks like #332 and #333 got reverted. Is that because of something here changed here?

**Comment by rossjrw** [comment]
Oops!

When I make a change to the source branch, after it's compiled I typically play a move, check that everything worked, and then hard reset it (I don't like being the top player of a team in my own project 😛). But this time you were hot on the draw and you played a move before I'd force-pushed the reset.

I'd un-reset it, but I don't have the commit from #333 (15eceee83c7c90ed7f20e0fab958b478bb679770) in my local and I'm not sure how to pull an orphaned commit. I've played a new move instead, #334 and #335, so feel free to play onto that. I've stolen your rosette, though.

**Comment by 1ethanhansen** [comment]
Dang i was hot on the draw because I wanted that rosette 😭
