### ISSUE TITLE
Seems like the math is wrong is some cases

### ISSUE THREAD

**Issue by MatissesProjects** [rossjrw/ur#3555]
![image](https://github.com/user-attachments/assets/c59694b1-a3b6-4692-9226-5bb4c6def02a)

This should be a capture move here not a 5 move

![image](https://github.com/user-attachments/assets/fb168b9e-ccec-4d94-909c-99578e1bfa30)

**Comment by Casper-Guo** [comment]
A piece on tile 8 (the center rosette) cannot be captured

You can review the game rules on Wikipedia. This repo implements the most basic rule set

**Comment by MatissesProjects** [comment]
my mistake on the rules, thanks for the info!
